version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/donate

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install --quiet

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run ci

orbs:
  jira: circleci/jira@1.0.5

workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify:
                job_type: build
                environment_type: development
