version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0
  aws-s3: circleci/aws-s3@3.0.0
  docker: circleci/docker@1.7.0
  jira: circleci/jira@1.1.2
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: thebiggive/donate-frontend-ci:latest
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    working_directory: ~/donate

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install --quiet

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run ci

  deploy-staging-static:
    docker:
      # This image's base Node version must match that used in the *root* `Dockerfile` (not the one in this directory)
      # which is the basis for ECS app builds. Otherwise the two builds will have different output hashes and the
      # dynamic app will reference static files that don't exist.
      - image: cimg/node:lts
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    steps:
      - checkout

      - run: npm config set puppeteer_skip_chromium_download true
      - run: npm install --quiet

      - run: npm run build:staging

      - aws-s3/sync:
          from: dist/browser
          to: 's3://tbg-staging-donate-static/d'
          arguments: |
            --acl public-read \
            --cache-control "max-age=31536000"

      - aws-s3/sync:
          from: dist/browser/assets
          to: 's3://tbg-staging-donate-static/assets'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

  deploy-regression-static:
    docker:
      # This image's base Node version must match that used in the *root* `Dockerfile` (not the one in this directory)
      # which is the basis for ECS app builds. Otherwise the two builds will have different output hashes and the
      # dynamic app will reference static files that don't exist.
      - image: cimg/node:lts
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    steps:
      - checkout

      - run: npm config set puppeteer_skip_chromium_download true
      - run: npm install --quiet

      - run: npm run build:regression

      - aws-s3/sync:
          from: dist/browser
          to: 's3://tbg-regression-donate-static/d'
          arguments: |
            --acl public-read \
            --cache-control "max-age=31536000"

      - aws-s3/sync:
          from: dist/browser/assets
          to: 's3://tbg-regression-donate-static/assets'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

  deploy-production-static:
    docker:
      # This image's base Node version must match that used in the *root* `Dockerfile` (not the one in this directory)
      # which is the basis for ECS app builds. Otherwise the two builds will have different output hashes and the
      # dynamic app will reference static files that don't exist.
      - image: cimg/node:lts
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    steps:
      - checkout

      - run: npm config set puppeteer_skip_chromium_download true
      - run: npm install --quiet

      - run: npm run build:production

      - aws-s3/sync:
          from: dist/browser
          to: 's3://tbg-production-donate-static/d'
          arguments: |
            --acl public-read \
            --cache-control "max-age=31536000"

      - aws-s3/sync:
          from: dist/browser/assets
          to: 's3://tbg-production-donate-static/assets'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  version: 2
  build-container:
    jobs:
      - docker/publish:
          context:
            - docker-hub-creds
          docker-password: DOCKER_HUB_ACCESS_TOKEN
          docker-username: DOCKER_HUB_USERNAME
          image: thebiggive/donate-frontend-ci
          path: ./.circleci # Working dir is project root
          tag: latest
    triggers:
      - schedule:
          cron: "3 5 * * *"
          filters:
            branches:
              only:
                - develop
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds
          post-steps:
            - jira/notify:
                job_type: build
                environment_type: development

  deploy-regression:
    jobs:
      - deploy-regression-static:
          filters:
            branches:
              only:
                - develop
          context:
            - docker-hub-creds
            - ecs-deploys # Includes AWS_REGION
      - aws-ecr/build-and-push-image:
          context:
            - ecs-deploys
          requires:
            - deploy-regression-static
          extra-build-args: '--build-arg BUILD_ENV=regression --build-arg FONTAWESOME_NPM_AUTH_TOKEN=${FONTAWESOME_NPM_AUTH_TOKEN}'
          repo: '${AWS_ECR_REPO_NAME}'
          region: AWS_REGION
          tag: 'regression,regression-${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_REGION
          family: 'tbg-regression-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX}'
          cluster-name: 'tbg-regression-${AWS_REGION}'
          container-image-name-updates: 'container=donate,tag=regression-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify-on-failure: ~

  deploy-staging:
    jobs:
      - deploy-staging-static:
          filters:
            branches:
              only:
                - develop
          context:
            - docker-hub-creds
            - ecs-deploys # Includes AWS_REGION
      - aws-ecr/build-and-push-image:
          context:
            - ecs-deploys
          requires:
            - deploy-staging-static
          extra-build-args: '--build-arg BUILD_ENV=staging --build-arg FONTAWESOME_NPM_AUTH_TOKEN=${FONTAWESOME_NPM_AUTH_TOKEN}'
          repo: '${AWS_ECR_REPO_NAME}'
          region: AWS_REGION
          tag: 'staging,staging-${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_REGION
          family: 'tbg-staging-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX}'
          cluster-name: 'tbg-staging-${AWS_REGION}'
          container-image-name-updates: 'container=donate,tag=staging-${CIRCLE_SHA1}'
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: staging
            - slack/notify:
                color: '#009900'
                message: 'We use rolling blue/green deploys. All visitors to staging will see the updated app version within ~20 minutes.'
                title: 'Staging: Donate frontend deployed!'
                title_link: 'https://donate-staging.thebiggivetest.org.uk'
            - slack/notify-on-failure: ~

  deploy-production:
    jobs:
      - deploy-production-static:
          filters:
            branches:
              only:
                - main
          context:
            - docker-hub-creds
            - ecs-deploys # Includes AWS_REGION
      - aws-ecr/build-and-push-image:
          context:
            - ecs-deploys
          requires:
            - deploy-production-static
          extra-build-args: '--build-arg BUILD_ENV=production --build-arg FONTAWESOME_NPM_AUTH_TOKEN=${FONTAWESOME_NPM_AUTH_TOKEN}'
          repo: '${AWS_ECR_REPO_NAME}'
          region: AWS_REGION
          tag: 'production,production-${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_REGION
          family: 'tbg-production-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX}'
          cluster-name: 'tbg-production-${AWS_REGION}'
          container-image-name-updates: "container=donate,tag=production-${CIRCLE_SHA1}"
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: production
            - slack/notify:
                color: '#009900'
                message: 'We use rolling blue/green deploys. All visitors to production will see the updated app version within ~20 minutes.'
                title: 'Production: Donate frontend deployed!'
                title_link: 'https://donate.thebiggive.org.uk'
            - slack/notify-on-failure: ~
